jugglerchris/rust-html2text

examples/html2text.rs

I've used the same argument-parsing crate as html2term, and used it to
implement a command-line option to set the column width of the
formatted output.
While I'm at it, I've also allowed specifying an input file name as a
positional argument, and the usual -o option to write to an output
file, so that html2text doesn't always have to be used with its
standard I/O handles redirected. However, the default behaviour if
neither of those options is present is to read from standard input and
write to standard output, so this change should be backwards
compatible in the sense that html2text run without arguments should
continue to do what it always has done. (However, running it _with_
arguments will now change behaviour, because the arguments aren't
ignored any more!)
This patch would look …

html2text: add a basic command-line parser.

---

src/lib.rs
src/render/mod.rs
src/render/text_renderer.rs

Convert the function-call recursion to use an explicit stack of unfinished work, to avoid overflowing the call stack.

Issue 2 deeply nested

---

src/lib.rs

As pointed out by Simon Tatham, the elements end up missing in the output.

Fix some problems when id attributes are on table elements.

---

examples/html2text.rs
src/lib.rs
src/render/text_renderer.rs

This is a useful option if the input HTML file has been generated by
an MUA which automatically inserts hyperlinks around parts of the
message that look like URLs or email addresses, and you want to
extract literal text from the message such as a shell transcript.
My technique is a bit bodgy. In text_renderer.rs I thought it was
cleaner to make a separate TrivialDecorator type than to complicate
the existing PlainDecorator with a boolean flag and endless ifs. But
then in html2text.rs I couldn't find a way to initialise a variable to
one of TrivialDecorator and PlainDecorator depending on the command-
line flag, so I used an extra layer of wrapper function, which surely
isn't the best way. But it seems to work.

html2text: add a --literal option to omit markup.

---

Cargo.toml
src/lib.rs

This PR updated all the dependencies to their latest versions. 
According to the CI tests here: https://dev.azure.com/liushuyu-011/liushuyu_011/_build/results?buildId=275 it seems to have fixed #14 completely.
You might notice I didn't use Appveyor because my Appveyor builds have trouble finding the `gcc` executable.
Thanks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jugglerchris/rust-html2text/15)

Update dependencies and minor fixes

---

src/lib.rs
src/render/mod.rs
src/render/text_renderer.rs

I'm not sure if this should be configurable or not, but at least on my corpus it was pretty desirable to have consecutive \<br\>s not get collapsed.

Don't collapse consecutive <br>s

---

src/lib.rs

This uses `tree_map_reduce()` to do the size estimation in a separate pass before the main rendering pass, preventing the possibly very deep recursion and stack exhaustion.

Fix size recursion

---

src/lib.rs
src/render/text_renderer.rs
src/tests.rs

Previously, there were three different entry points for html2text:
from_read, from_read_with_decorator and from_read_rich.  This had two
drawbacks:
Firstly, the user always had to parse and render the HTML at the same
time.  But there are use cases where the user wants to render the same
HTML document using different widths or decorators.  This involved
parsing the document multiple times.
Secondly, it was impossible to create rich text with a custom decorator.
This would have required a new function from_read_rich_with_decorator.
This patch introduces a new entry point for the pubic API, the parse
function.  It reads and parses the HTML document and returns a
RenderTree object.  This object can then be rendered into a RenderedText
object using a custom decorator or the default plain and …

Add parse function as a new entry point

---

examples/html2term.rs
src/render/text_renderer.rs

This patch adds the tagged_strings method to TaggedLine that is a
shorthand for:
self.iter().filter_map(|tle| match tle {
TaggedLineElement::Str(ts) => Some(ts),
_ => None,
})
Many TaggedLine consumers don’t care about fragments and only want to
iterate over the tagged strings.

Add tagged_strings method to TaggedLine

---

CHANGELOG.md

Previosuly, half of the rendered text of the changelog was struck out
because of an unescaped and unclosed strikout tag.  This patch fixes the
formatting by wrapping the tag in backticks.

Fix strikeout tag in changelog

---

src/render/text_renderer.rs

This patch adds the width method to TaggedString that uses the
unicode_width crate to calculate the display width of the tagged string.
This makes TaggedString more consistent with TaggedLine, which already
has a width method, and it allows users of the crate to easily query the
width without having to add the unicode_width dependency themselves.

Add width method for TaggedString

---

src/render/text_renderer.rs
src/tests.rs

The TextRenderer::into_lines method calls the TextDecorator::finalise
method and appends the returned lines to the rendered lines, re-wrapping
them if required.  Previously, it would concatenate all strings into
lines and append one TaggedString without annotations per line.
With this patch, we keep the original tagged strings and just split them
if required.  This means that the annotations are no longer stripped
from the lines returned by finalise.  We also add a new test case that
checks that these annotations are present.
Fixes #39.

Keep annotations in TextRenderer::into_lines

---

src/render/text_renderer.rs

In commit 17940794eacceb36679ca04e54573e32ae8906ca, we added the `tagged_strings` method to `TaggedLine` that returns an iterator over the tagged strings.  In this patch, we also add a `into_tagged_strings` method that takes ownership of the tagged strings.  This is useful when converting a `TaggedLine`, for example in the `TaggedLine::width` method or in external crates that process the `TaggedLine` before rendering it.

Add into_tagged_strings method to TaggedLine

---

src/lib.rs
src/render/mod.rs
src/render/text_renderer.rs
src/tests.rs

Move hard-coded prefix in header, blockquote, unordered list and ordered list into `TextDecrator` to allow customize. 
Make `TrivialDecorator` return empty string for these prefix. (Maybe should keep ordered list index?)

Remove hard-coded decorators

---

.circleci/config.yml
Cargo.toml
src/lib.rs
src/render/text_renderer.rs
src/tests.rs

There were two problems:
* An integer overflow when calculating column widths
* Trying to allocate a string of usize::MAX spaces.
Things should behave a little better with large widths.

Fix issue with small table and usize::MAX width.

---

src/lib.rs

In text mode, we could end up with a column expected to be zero size, but which actually had some content only (`[3] http://example.org`).

Account for link targets when calculating <a> size.

---

src/render/text_renderer.rs

This is harmless as long as we don't try to put any text into them.

Remove asserts on zero-width builders.

---

src/render/text_renderer.rs
src/tests.rs

Let me know if you want to change the names of the functions or do something else entirely.

Preserve empty lines in <pre></pre> blocks

---

examples/html2term.rs
src/lib.rs
src/render/mod.rs
src/render/text_renderer.rs
src/tests.rs

This PR adds logic to include an img tag's `src` attribute value in the `RichAnnotation::Image` enum that's emitted during decoration.

Emit img src in RichAnnotation (fixes #72)

---

.circleci/config.yml
Cargo.toml
src/lib.rs

This aims to become a more general way of adding configuration for the translation.

Add an experimental Config struct.

---

src/lib.rs

Fixes #88.
Perhaps we should move to returning a `Result`, but this at least should stop the OOM and make errors easier to debug.

Panic when passed a zero width instead of OOM.

---

src/lib.rs
src/tests.rs

Although HTML5 forbids colspan=0, it's interpreted in some browsers as meaning "the rest of the columns", so handle this by replacing it with the expanded size before rendering.
Fixes #90.

Handle the colspan=0 case.

---

src/lib.rs
src/render/text_renderer.rs

The doc comment for use_doc_css had an unescaped <style>, which was emitted unchanged into the HTML by rustdoc and ate the whole of the rest of the HTML output file. I've escaped it so that it's printed literally.
TextDecorator's top-level documentation had a paragraph ending with an unfinished sentence. I've finished it as best I could, although of course I may have guessed wrong!
Several decorator methods had the word 'an' before a consonant. I suspect it was copy-paste error from 'after an em' just above.

Fix nits in documentation.

---

src/lib.rs

`<i>` and `<ins>` are treated the same as `<em>`. That seems a bit weird because `<ins>` is canonically shown as underlining whereas `<i>` is canonically italic, so they shouldn't be the same. On the other hand, `<i>` and `<em>` _are_ canonically the same, and underlining is often the most sensible thing to do with `<em>`, so perhaps in this environment it's not totally silly. Anyway, it at least means those two tags aren't completely ignored.
`<del>` is treated the same as `<s>`, for strikeout.

Simplistic support for <i>, <ins> and <del>.

---

CHANGELOG.md
Cargo.toml
src/lib.rs

Some of the Config methods weren't passing the context to the renderer.

Fix an issue which caused the max wrap width not to work.

---

src/lib.rs

It was already being returned from some functions, and is pub, but crate::RcDom wasn't pub.

Mark RcDom as pub.

---

src/css.rs
src/lib.rs
src/tests.rs

These aren't very standard but are used in the wild. The specific case for <font color="..."> has been removed.

CSS: handle color/bgcolor attributes.

---

examples/html2text.rs

This lets you enable CSS for the `display: none` and similar handling while still using the default colours added for <strong> etc.
Fixes #138.

Add --ignore-css-colour option to html2text example.

---

Cargo.toml

Also increments version. Please push a new release. 
Pinning the version of dashmap means that crates that depend on html2text cannot use a newer version of dashmap

Remove unused dashmap dependency

---

examples/html2term.rs
examples/html2text.rs
src/lib.rs
src/render/mod.rs
src/render/text_renderer.rs

The main imports needed from this crate are behind extra modules, this flattens the externally visible module hierarchy to `html2text::render::{..}`

Flatten pub exported paths

---

CHANGELOG.md
Cargo.toml
src/lib.rs
src/render/mod.rs
src/render/text_renderer.rs
src/tests.rs

There was a missing case in `wrap_render_nodes()`; table row nodes need to wrap the nested contents so that the TableRow nodes are still direct children of the TableBody.
Fixes #155

Fix issue 155: table rows with styling going missing.

---

src/lib.rs
src/render/text_renderer.rs

Adds an option to disable wrapping of links. This is because wrapping the links breaks auto-linkification in many cases, and some users (including me!) might like to disable it.
The default behaviour remains the same.

Add option to disable wrapping links

---

README.md
examples/html2term.rs
src/lib.rs
src/tests.rs

replace panicing APIs with APIs that return errors

---

src/css.rs
src/css/parser.rs
src/lib.rs
src/render/mod.rs
src/render/text_renderer.rs
src/tests.rs

Add support for CSS `white-space` values `normal`, `pre`, and `pre-wrap`.
Change the implementation of `<pre>` - it's now treated the same as `<p>` with `white-space: pre` (even with CSS disabled - the style is constructed directly rather than going through a CSS parser).
Closes #157

Support white-space: pre-wrap

---

src/lib.rs
src/render/mod.rs
src/render/text_renderer.rs
src/tests.rs

Treat `<pre>` specially after all - the preformat decorations should only be used there, not on `<p>` with the same wrapping info.

Further fixes for pre-wrap

---

examples/html2text.rs
src/css/parser.rs
src/markup5ever_rcdom.rs
src/render/text_renderer.rs
src/tests.rs

Two CSS fixes:
* Support background: color (as well as already-supported background-color: color)
* Fix some edge cases with whitespace styling

Add --show-dom and small CSS fixes

---

src/css.rs
src/css/parser.rs
src/lib.rs
src/markup5ever_rcdom.rs
src/render/mod.rs
src/render/text_renderer.rs

I was taking a closer look at error handling, I noticed that some small changes can make it simpler to understand where errors are coming from.
The two most significant changes are to introduce a specific rendering error type that is only converted to the library-wide `Error` as late as possible and to move Ok-wrapping of closure return types as close to the `cons` identifier as possible. This last change permits grepping for the `cons` identifier and one can see at a glance whether the closure can error or not.

Error wrapping

---

CHANGELOG.md
Cargo.toml
examples/html2text.rs
src/css/parser.rs
src/lib.rs

Some e-mails seem to use `<table bgcolor="123456">` - note no `#`, not to mention that `bgcolor` is heavily discouraged in favour of CSS.  However, Firefox and Chromium both interpret this as equivalent to `background-color: #123456`, and the e-mail was partly unreadable without (white-on-white).
Also add `html2text --show-render` to help debugging the render tree.

Fix handling of some invalid colours.

---

Cargo.toml
examples/html2term.rs
examples/html2text.rs
src/css.rs
src/css/parser.rs
src/lib.rs
src/markup5ever_rcdom.rs
src/render/text_renderer.rs
src/tests.rs

This allows a simple debug mode where a portion of the document is shown as the raw DOM rather than rendered normally.
Also a couple of bug fixes.

Add `:nth-child()` and (as a debug extension) `display: x-raw-dom`.

---

.github/workflows/ci.yml
CHANGELOG.md
Cargo.toml
examples/html2text.rs
src/lib.rs
src/render/text_renderer.rs
src/tests.rs

This is similar to rich, but for things like bold and code blocks, don't include the textual decorations which can be handled by (for example) terminal attributes.

Add config::rich_no_decorate()

---

src/lib.rs

Thanks so much for this effort that is a great fit for my `HTML -> plaintext` and `HTML -> Markdown` use cases! 🥳 
This is a simple change that adds support for the HTML `h5` and `h6` tags to complement the existing parsing of `h1`, `h2`, `h3`, and `h4`.

Support `h5` and `h6` tags

---

CHANGELOG.md
examples/html2text.rs
src/css.rs
src/css/parser.rs
src/css/types.rs
src/lib.rs
src/render/text_renderer.rs
src/tests.rs

Instead of using the decorator to add decorations around `<em>` and similar tags, we internally now use CSS features instead - this means it can be enabled or not independent of the decorator.
* Add new `config::plain_no_decorate()`, which leaves off the decoration around `*bold*` text etc.
* `config::plain()` is equivalent to `config::plain_no_decorate().do_decorate()`
* The `RichDecorator` no longer adds these decorations by default, but `config::rich().do_decorate()` is available.
* With the `css` feature enabled, `::before` and `::after` pseudo-elements are supported along with the `content: "foo"` style, which is used to implement the above.  This can be used to tweak the decoration with, for example, `add_agent_css()`.

Use CSS for simple decorations.

---

CHANGELOG.md
Cargo.lock
Cargo.toml
examples/html2text.rs
src/css.rs
src/css/parser.rs
src/lib.rs

Allow for syntax highlighting `<pre>` blocks (with "css_ext" feature)
Add `Config::register_highlighter()`, which can add a
syntax highlighting function associated with a language name. This can
be used with a CSS declaration `x-syntax: name`.  The highlighter
is passed a raw string containing all the text inside the `<pre>`, not
including any elements, and returns a list of styled spans.  Foreground
and background colours are currently supported.
The CSS extensions are no longer available in document/author CSS, since
we're likely to want to view untrusted HTML.  In an application which
wants to give HTML the ability to do so, it can be done via a class and
an extra agent rule referring to that class.
Add `--syntax` option to the html2text example to register a `rs` (rust)
highlighter as …

Add support for external syntax highlighting.

---

CHANGELOG.md
examples/html2text.rs
src/css.rs
src/css/parser.rs
src/lib.rs
src/render/text_renderer.rs

CSS: Support basic attribute selectors (`div[attr="bar"]`).                            
Syntax highlighting uses the priority of the `x-syntax` rule.                        
With `pad_block_width` enabled, do a better job of padding blocks.   In particular, the padding gets the block's background colour (when CSS etc. are being used).

Implement attribute selectors, and improve block padding.

---

Cargo.lock
examples/html2text.rs
src/lib.rs
src/markup5ever_rcdom.rs
src/tests.rs

Overhaul of the syntax highlighting:
* `x-syntax` is no longer limited to `<pre>` elements
* Elements within a syntax-highlighted region are preserved
* Regions with `display: x-raw-dom` can also be highlighted as HTML
Also fix an issue with serialization back to HTML (don't lose the root element).

Improvements to syntax highlighting

---

src/render/text_renderer.rs
src/tests.rs

In the new test case in tests.rs, the line must be broken before the final word of the paragraph, so that that word appears on a line by itself. If that test is added by itself, without the rest of the changes in this commit, then it will fail, because the final line of the paragraph comes out with a spurious leading space.
The last word of the paragraph differs from everything else because it's written by WrappedBlock::flush() at the end of the paragraph, instead of by a call to flush_word() from within add_text(). And flush() calls flush_word(WhiteSpace::Normal), without any test to see whether Normal was the appropriate ws_mode.
In this case, it wasn't. The whole paragraph is in PreWrap, and in that mode, self.word usually contains a word of the paragraph plus the whitespace that …

Fix spurious space before orphan words in pre-wrap mode.

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/render/text_renderer.rs

Fixes a bug with tables with rowspan in rich mode. This was caused by an assertion failure, which was there to catch part of missing implementation.

Update for 0.15.5.

---

.circleci/config.yml
src/css/parser.rs
src/lib.rs
src/markup5ever_rcdom.rs
src/render/text_renderer.rs
src/tests.rs

In commit 634cee8 the rendering of multiple `<pre>` elements changed. This was not covered by a test, and now it is.
On a secondary note, the layout prior to that commit was more in line with how browsers chose to render it. If we remove the css we get `html2text` and Chrome to agree on both pre-634c and post-634c layouting, it's the CSS that makes the difference.
The added fragment is a bit larger than necessary, to show how this appeared in a real email, but we can trim it down to be more minimal.
Sidenote 2, CI is broken on master.

Test layout of multiple `<pre>` elements
